### PR TITLE
Add copy-button and JavaScript to copy text to user clipboard

### LINKED ISSUE #10: [Feature] Add a copy button
## Description

Add a copy button on the right side of the shortened URL to copy the shortened URL to the clipboard.

### PR DESCRIPTION
**Pull request by DJStowe**
## Fixes

Fixes #10 by @SAMAD101 

## Description

Added copy-button to showliberate.html
Added inline JavaScript to copy text in showliberate.html
added formatting for copy-button into base.html 
Deleted some whitespace that was making the pre-commit hooks mad in showliberate.html and base.html

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
      visible errors.

[best_practices]: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

### CODE REVIEW

**Comment by SAMAD101** [comment]
Can you please put a small video showing it in action @DJStowe

**Comment by DJStowe** [comment]
Running out of dropbox space so I'll delete it after you're done
Video Here:
https://www.dropbox.com/scl/fi/kf4gf0d8aop50fu1zj6ub/Add-Copy-Button.mkv?rlkey=cgqmfqcknx8x31qynszxwrb1o&dl=0

**Comment by DJStowe** [comment]
Video Here:
https://www.dropbox.com/scl/fo/vgwhcmoootqijsci3rm9n/h?rlkey=y0x62z84cnqn8uv02s0ie7gp6&dl=0

**Comment by SAMAD101** [comment]
> Video Here: https://www.dropbox.com/scl/fo/vgwhcmoootqijsci3rm9n/h?rlkey=y0x62z84cnqn8uv02s0ie7gp6&dl=0

thank you for contributing

**Pull request merged**
