### PR TITLE
Add unittest

### PR DESCRIPTION
**Pull request by Jonatan-Chaverri**
## Related to 

Related to #8  by @SAMAD101 

## Description

Add unittest for the main APIs.

## Technical details

Adding pytest using FastAPI test client and pytest-mock library.

## Tests

You can run the test by running
`pytest tests`

## Screenshots

Screenshot 2024-01-20 at 16 36 38

## Checklist

- [x ] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
      visible errors.

[best_practices]: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

### CODE REVIEW

**Comment by Jonatan-Chaverri** [comment]
I can also create a github workflow in order to check unittest passing before merging PRs. Let me know.

**Comment by SAMAD101** [comment]
> I can also create a github workflow in order to check unittest passing before merging PRs. Let me know.

LGTM
That would be great if you can do that!

**Comment by Jonatan-Chaverri** [comment]
@SAMAD101 I added the workflow, however I think you need to approve it before it can run. You can check the configured actions settings for the repo and enable external contributors to run workflows.

**Comment by SAMAD101** [comment]
Thank you very much for contributing @Jonatan-Chaverri

**Pull request merged**
